---
- name: Check if certbot binary exists
  ansible.builtin.stat:
    path: "/usr/bin/certbot"
  register: certbot_stat

- name: Query certbot version if present
  ansible.builtin.command:
    cmd: "/usr/bin/certbot --version"
  register: certbot_version_cmd
  ignore_errors: true
  changed_when: false

- name: Install certbot package
  become: true
  ansible.builtin.package:
    name: "{{ certbot.package_name | default('certbot') }}"
    state: present
  when:
    - not (certbot_version_cmd.stdout is defined and ('certbot' in certbot_version_cmd.stdout))
