---
- name: Check goenv present
  ansible.builtin.stat:
    path: /usr/local/go
  register: goenv_dir

- name: Git checkout goenv
  ansible.builtin.git:
    repo: 'https://github.com/go-nv/goenv.git'
    dest: ~/.goenv
    version: master
    update: true
  when: not goenv_dir.stat.exists

- name: Install golang
  become: true
  changed_when: true
  ansible.builtin.command: goenv install {{ golang.version }}.
  when: not golang_dir.stat.exists
