---
- name: Check goenv present
  stat:
    path: /usr/local/go
  register: goenv_dir

- name: Git checkout goenv
  git:
    repo: 'https://github.com/go-nv/goenv.git'
    dest: ~/.goenv
    version: master
    update: yes
  when: not goenv_dir.stat.exists

- name: Install golang
  become: true
  shell: |
    goenv install {{ golang.version }}.
  when: not golang_dir.stat.exists
