---
- name: Install zsh
  become: true
  dnf:
    name: zsh
    state: latest

- name: Set zsh as default shell
  become: true
  shell: |
    chsh -s /usr/bin/zsh "{{ user.name }}"

- name: Create default .zshrc
  become: true
  become_user: "{{ user.name }}"
  template:
    src: ../../../../templates/zshrc.j2
    dest: "~/.zshrc"
    mode: 0644
    force: false
