- name: Set up the K8s workstations
  hosts: "*"
  roles:
    - role: k8s/tools
      tags: k8s
    - role: k8s/k8s-admin-shell
      tags: k8s
    - role: k8s/k8s-scripts
      tags: k8s
    - role: productivity-tools/tools
      tags: productivity
    - role: productivity-tools/linux-tools
      tags: productivity
    - role: productivity-tools/oh-my-zsh
      tags: productivity
    - role: ubuntu/essential-packages
      tags: ubuntu
    - role: ubuntu/network-packages
      tags: ubuntu
