- name: Set up the K8s workstations
  hosts: "*"
  become: true
  roles:
    - role: k8s/tools
      tags: k8s
    - role: ai/tools
      tags: ai
    - role: k8s/k8s-admin-shell
      tags: git
    - role: k8s/k8s-scripts
      tags: git
    - role: networking
      tags: networking
    - role: productivity-tools/linux-tools
      tags: git
    - role: productivity-tools/tools
      tags: productivity
    - role: productivity-tools/oh-my-zsh
      tags: zsh
    - role: ubuntu/essential-packages
      tags: ubuntu
    - role: ubuntu/network-packages
      tags: ubuntu
