- name: Install productivity tools
  hosts: "*"
  vars:
    ansible_shell_executable: /usr/bin/zsh
  roles:
    - role: productivity-tools/linux-tools
    - role: productivity-tools/tools
    - role: productivity-tools/oh-my-zsh


