FILENAME: .gotask.yaml
version: '3'

tasks:

  ansible:run:
    desc: Run Ansible playbook with dynamic tag, inventory and role file
    vars:
      TAG: "{{.TAG | default .tag | default \"\"}}"
      INVENTORY: "{{.INVENTORY | default .inventory | default \"\"}}"
      PLAYBOOK: "{{.PLAYBOOK | default .playbook | default \"site.yml\"}}"
    preconditions:
      - sh: 'test -n "{{.INVENTORY}}"'
        msg: INVENTORY variable is required, pass with INVENTORY=path/to/inventory or --inventory
    cmds:
      - |
        set -e
        TAG_ARG=""
        if [ -n "{{.TAG}}" ]; then
          TAG_ARG="--tags {{.TAG}}"
        fi
        INVENTORY_ARG="--inventory {{.INVENTORY}}"
        ansible-playbook --become-password-file=.pwd {{.PLAYBOOK}} ${TAG_ARG} ${INVENTORY_ARG} ${ROLE_FILE_ARG}

  ansible:run:productivity:
    desc: Run productivity roles
    cmds:
      - task: ansible:run
        vars:
          INVENTORY: inventory/localhost.yaml
          PLAYBOOK: localhost.yaml
          TAG: productivity

  ansible:run:ai:
    desc: Run ai roles
    cmds:
      - task: ansible:run
        vars:
          INVENTORY: inventory/localhost.yaml
          PLAYBOOK: localhost.yaml
          TAG: ai
