- name: Copy ssh public key
  become: yes
  become_user: "{{ user.name }}"
  shell: |
    mkdir ~/.ssh
    if [ ! -f ~/.ssh/authorized_keys ]; then
      touch ~/.ssh/authorized_keys
    fi
    if ! grep -q "ssh-rsa {{ user.ssh_pub_key }}" ~/.ssh/authorized_keys; then
      echo "ssh-rsa {{ user.ssh_pub_key }}" >> ~/.ssh/authorized_keys
    fi

- name: Enable ssh public key authentication
  become: yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '#PubkeyAuthentication yes'
    line: 'PubkeyAuthentication yes'

