- name: Check ssh dir present
  stat:
    path: /home/{{ user.name }}/.ssh
  register: ssh_dir

- name: Copy ssh public key
  become: true
  become_user: "{{ user.name }}"
  shell: |
    mkdir ~/.ssh
    if [ ! -f ~/.ssh/authorized_keys ]; then
      touch ~/.ssh/authorized_keys
    fi
    if ! grep -q "{{ user.ssh_pub_key }}" ~/.ssh/authorized_keys; then
      echo "{{ user.ssh_pub_key }}" >> ~/.ssh/authorized_keys
    fi
  when: not ssh_dir.stat.exists

- name: Enable ssh public key authentication
  become: true
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '#PubkeyAuthentication yes'
    line: 'PubkeyAuthentication yes'
  when: not ssh_dir.stat.exists

- name: Add or update AllowUsers directive
  become: yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'AllowUsers .*'
    line: "AllowUsers {{ user.name }}"
