---
- name: Install essential packages
  become: true
  apt:
    name: '{{ item }}'
    state: latest
    update_cache: yes
  with_items: '{{ essential_packages }}'

- name: Set VIM as default editor
  become: true
  shell: |
    update-alternatives --set editor /usr/bin/vim.basic

- name: Set zsh as default shell
  become: true
  shell: |
    chsh -s $(which zsh)
