---
- name: Install essential packages
  become: yes
  apt:
    name: '{{ item }}'
    state: latest
    update_cache: yes
  with_items: '{{ essential_packages }}'

- name: Set VIM as default editor
  become: yes
  shell: |
    update-alternatives --set editor /usr/bin/vim.basic
