---
- name: Install essential packages
  become: true
  ansible.builtin.apt:
    name: '{{ item }}'
    state: latest
    update_cache: true
  with_items: '{{ essential_packages }}'

- name: Set VIM as default editor
  become: true
  changed_when: true
  ansible.builtin.command: update-alternatives --set editor /usr/bin/vim.basic

- name: Set zsh as default shell
  become: true
  changed_when: true
  ansible.builtin.command: chsh -s $(which zsh)
