---
- name: Check k8s-admin-shell present
  become: true
  become_user: "{{ user.name }}"
  stat:
    path: ~/projects/github/k8s-admin-shell
  register: k8s_admin_shell

- name: Git checkout
  become: true
  become_user: "{{ user.name }}"
  git:
    repo: 'https://github.com/fritzduchardt/k8s-admin-shell.git'
    dest: ~/projects/github/k8s-admin-shell
    version: master
    update: yes
  when: not k8s_admin_shell.stat.exists
