---
- name: Install zsh
  become: yes
  apt:
    package: 'zsh'
    state: present
    update_cache: yes

- name: Set zsh as default shell
  become: yes
  shell: |
    chsh -s /usr/bin/zsh "{{ user.name }}"


- name: Create default .zshrc
  become: yes
  become_user: "{{ user.name }}"
  template:
    src: ../../../../templates/zshrc.j2
    dest: "~/.zshrc"
    mode: 0644
    force: false
