---
- name: Check linux-tools present
  become: true
  become_user: "{{ user.name }}"
  stat:
    path: ~/projects/github/linux-tools
  register: linux_tools
  
- name: Git checkout
  become: true
  become_user: "{{ user.name }}"
  git:
    repo: 'https://github.com/fritzduchardt/linux-tools.git'
    dest: ~/projects/github/linux-tools
    version: master
    update: yes
  when: not linux_tools.stat.exists
