---
- name: Check bat present
  stat:
    path: /usr/local/bin/bat-{{ versions.bat }}
  register: bat_bin

- name: Install bat
  become: true
  shell: |
    curl -L {{ download_urls.bat }} | \ 
    tar -xzf - --strip-components=1 bat-{{ versions.bat }}-i686-unknown-linux-musl/bat
    install -m 555 bat /usr/local/bin/bat-{{ versions.bat }}
    ln -sf /usr/local/bin/bat-{{ versions.bat }} /usr/local/bin/bat
    rm bat
  when: not bat_bin.stat.exists
