---
- name: Check fd present
  stat:
    path: /usr/local/bin/fd-{{ versions.fd }}
  register: fd_bin

- name: Install fd
  become: true
  shell: |
    curl -L {{ download_urls.fd }} | \ 
    tar -xzf - --strip-components=1 --wildcards "*/fd"
    install -m 555 fd /usr/local/bin/fd-{{ versions.fd }}
    ln -sf /usr/local/bin/fd-{{ versions.fd }} /usr/local/bin/fd
    rm fd
  when: not fd_bin.stat.exists
