---
- name: Check fd present
  stat:
    path: /usr/local/bin/fd-{{ fd.version }}
  register: fd_bin

- name: Install fd
  become: yes
  shell: |
    curl -L https://github.com/sharkdp/fd/releases/download/{{ fd.version }}/fd-{{ fd.version }}-x86_64-unknown-linux-musl.tar.gz | \ 
    tar -xzf --strip-components=1 fd-{{ fd.version }}-x86_64-unknown-linux-musl/fd
    install -m 555 fd /usr/local/bin/fd-{{ fd.version }}
    ln -sf /usr/local/bin/fd-{{ fd.version }} /usr/local/bin/fd
    rm fd
  when: not fd_bin.stat.exists
