---
- name: Check fzf present
  ansible.builtin.stat:
    path: /usr/local/bin/fzf-{{ versions.fzf }}
  register: fzf_bin

- name: Install fzf
  become: true
  changed_when: true
  ansible.builtin.shell:
    executable: /usr/bin/bash
    cmd: |
      curl -o fzf.tar.gz -L {{ download_urls.fzf }}
      tar -xzf fzf.tar.gz fzf
      install -m 555 fzf /usr/local/bin/fzf-{{ versions.fzf }}
      ln -sf /usr/local/bin/fzf-{{ versions.fzf }} /usr/local/bin/fzf
      rm fzf
      rm fzf.tar.gz
#  when: not fzf_bin.stat.exists
