---
- name: Check fzf present
  stat:
    path: /usr/local/bin/fzf-{{ fzf.version }}
  register: fzf_bin

- name: Install fzf
  become: true
  shell: |
    curl -L https://github.com/junegunn/fzf/releases/download/{{ fzf.version }}/fzf-{{ fzf.version }}-linux_amd64.tar.gz | \
    tar -xzf - fzf
    install -m 555 fzf /usr/local/bin/fzf-{{ fzf.version }}
    ln -sf /usr/local/bin/fzf-{{ fzf.version }} /usr/local/bin/fzf
    rm fzf
  when: not fzf_bin.stat.exists
