---
- name: Check fzf present
  stat:
    path: /usr/local/bin/fzf-{{ versions.fzf }}
  register: fzf_bin

- name: Install fzf
  become: true
  shell: |
    curl -L {{ download_urls.fzf }} | \
    tar -xzf - fzf
    install -m 555 fzf /usr/local/bin/fzf-{{ versions.fzf }}
    ln -sf /usr/local/bin/fzf-{{ versions.fzf }} /usr/local/bin/fzf
    rm fzf
  when: not fzf_bin.stat.exists
