---
- name: Check lazygit present
  stat:
    path: /usr/local/bin/lazygit-{{ lazygit.version }}
  register: lazygit_bin

- name: Install lazygit
  become: yes
  shell: |
    curl -LO https://github.com/jesseduffield/lazygit/releases/download/v{{ lazygit.version }}/lazygit_{{ lazygit.version }}_Linux_x86_64.tar.gz
    tar -xzf lazygit_{{ lazygit.version }}_Linux_x86_64.tar.gz lazygit
    install -m 555 lazygit /usr/local/bin/lazygit-{{ lazygit.version }}
    ln -sf /usr/local/bin/lazygit-{{ lazygit.version }} /usr/local/bin/lazygit
    rm lazygit
  when: not lazygit_bin.stat.exists

- name: Create alias for lazygit
  become: yes
  become_user: "{{ user.name }}"
  shell: |
    source ~/.zshrc
    add_alias.sh lg "lazygit"
  when: not lazygit_bin.stat.exists
