---
- name: Check lazygit present
  ansible.builtin.stat:
    path: /usr/local/bin/lazygit-{{ versions.lazygit }}
  register: lazygit_bin

- name: Install lazygit
  become: true
  changed_when: true
  ansible.builtin.shell: |
    set -eo pipefail
    curl -L {{ download_urls.lazygit }} | \
    tar -xzf - lazygit
    install -m 555 lazygit /usr/local/bin/lazygit-{{ versions.lazygit }}
    ln -sf /usr/local/bin/lazygit-{{ versions.lazygit }} /usr/local/bin/lazygit
    rm lazygit
  when: not lazygit_bin.stat.exists
