---
- name: Check mcfly present
  ansible.builtin.stat:
    path: /usr/local/bin/mcfly-{{ versions.mcfly }}
  register: mcfly_bin

- name: Install mcfly
  become: true
  changed_when: true
  ansible.builtin.shell:
    executable: /usr/bin/bash
    cmd: |
      set -eo pipefail
      curl -L {{ download_urls.mcfly }} | \ 
      tar -xzf - mcfly
      install -m 555 mcfly /usr/local/bin/mcfly-{{ versions.mcfly }}
      ln -sf /usr/local/bin/mcfly-{{ versions.mcfly }} /usr/local/bin/mcfly
      rm mcfly
  when: mcfly_enabled and not mcfly_bin.stat.exists
