---
- name: Check nvim present
  stat:
    path: /usr/local/bin/nvim-{{ nvim.version }}
  register: nvim_bin

- name: Install nvim
  become: true
  shell: |
    curl -L https://github.com/neovim/neovim/releases/download/v0.9.5/nvim-linux64.tar.gz | \ 
    tar -xzf - --strip-components=2 nvim-linux64/bin/nvim
    install -m 555 nvim /usr/local/bin/nvim-{{ nvim.version }}
    ln -sf /usr/local/bin/nvim-{{ nvim.version }} /usr/local/bin/nvim
    rm nvim
  when: not nvim_bin.stat.exists
