---
- name: Check rg present
  stat:
    path: /usr/local/bin/rg-{{ rg.version }}
  register: rg_bin

- name: Install ripgrep
  become: true
  shell: |
    curl -LO https://github.com/BurntSushi/ripgrep/releases/download/{{ rg.version }}/ripgrep-{{ rg.version }}-x86_64-unknown-linux-musl.tar.gz
    tar -xzf ripgrep-{{ rg.version }}-x86_64-unknown-linux-musl.tar.gz --strip-components=1 ripgrep-{{ rg.version }}-x86_64-unknown-linux-musl/rg
    install -m 555 rg /usr/local/bin/rg-{{ rg.version }}
    ln -sf /usr/local/bin/rg-{{ rg.version }} /usr/local/bin/rg
    rm rg
  when: not rg_bin.stat.exists
