---
- name: Check rg present
  stat:
    path: /usr/local/bin/rg-{{ versions.rg }}
  register: rg_bin

- name: Install ripgrep
  become: true
  shell: |
    curl -L {{ download_urls.rg }} | \
    tar -xzf - --strip-components=1 --wildcards "*/rg"
    install -m 555 rg /usr/local/bin/rg-{{ versions.rg }}
    ln -sf /usr/local/bin/rg-{{ versions.rg }} /usr/local/bin/rg
    rm rg
  when: not rg_bin.stat.exists
