---
- name: Check yq present
  stat:
    path: /usr/local/bin/yq-{{ yq.version }}
  register: yq_bin

- name: Install yq
  become: true
  shell: |
    curl -sSL https://github.com/mikefarah/yq/releases/download/{{ yq.version }}/yq_linux_amd64.tar.gz | \
    tar -xzf - ./yq_linux_amd64
    install -m 555 ./yq_linux_amd64 /usr/local/bin/yq-{{ yq.version }}
    ln -sf /usr/local/bin/yq-{{ yq.version }} /usr/local/bin/yq
    rm -rf ./yq_linux_amd64
  when: not yq_bin.stat.exists
