---
- name: Check zoxide present
  ansible.builtin.stat:
    path: /usr/local/bin/zoxide-{{ versions.zoxide }}
  register: zoxide_bin

- name: Install zoxide
  become: true
  changed_when: true
  ansible.builtin.shell:
    executable: /usr/bin/bash
    cmd: |
      curl -o zoxide.tar.gz -L {{ download_urls.zoxide }}
      tar -xzf zoxide.tar.gz
      install -m 555 zoxide /usr/local/bin/zoxide-{{ versions.zoxide }}
      ln -sf /usr/local/bin/zoxide-{{ versions.zoxide }} /usr/local/bin/zoxide
      rm zoxide
      rm zoxide.tar.gz
  when: not zoxide_bin.stat.exists
