---
- name: Check zoxide present
  ansible.builtin.stat:
    path: /usr/local/bin/zoxide-{{ versions.zoxide }}
  register: zoxide_bin

- name: Install zoxide
  become: true
  changed_when: true
  ansible.builtin.shell: |
    set -eo pipefail
    curl -L {{ download_urls.zoxide }} | \ 
    tar -xzf - zoxide
    install -m 555 zoxide /usr/local/bin/zoxide-{{ versions.zoxide }}
    ln -sf /usr/local/bin/zoxide-{{ versions.zoxide }} /usr/local/bin/zoxide
    rm zoxide
  when: not zoxide_bin.stat.exists
