essential_packages:
    - build-essential
    - ca-certificates
    - curl
    - wget
    - git
    - gnupg
    - htop
    - httpie
    - jq
    - skopeo
    - software-properties-common
    - tree
    - vim
    - wget
    - zsh
