---
- name: Git checkout
  become: true
  become_user: "{{ user.name }}"
  ansible.builtin.git:
    repo: 'https://github.com/fritzduchardt/k8s-admin-shell.git'
    dest: ~/projects/github/k8s-admin-shell
    version: master
    update: true
