---
- name: Check docker present
  ansible.builtin.stat:
    path: /etc/apt/keyrings/docker.gpg
  register: docker

- name: Prepare Docker
  become: true
  changed_when: true
  ansible.builtin.shell: |
    sudo install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    sudo chmod a+r /etc/apt/keyrings/docker.gpg

    # Add the repository to Apt sources:
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  when: not docker.stat.exists

- name: Install Docker
  become: true
  ansible.builtin.apt:
    name: '{{ item }}'
    state: latest
    update_cache: true
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
  when: not docker.stat.exists

- name: Configure Docker
  become: true
  changed_when: true
  ansible.builtin.command: "sudo usermod -aG docker {{ user.name }}"
  when: not docker.stat.exists
