---
- name: Check copacetic present
  ansible.builtin.stat:
    path: /usr/local/bin/copacetic-{{ copacetic.version }}
  register: copacetic_bin

- name: Install copacetic
  become: true
  changed_when: true
  ansible.builtin.shell:
    executable: /usr/bin/bash
    cmd: |
      set -eo pipefail
      curl -fsSL https://github.com/project-copacetic/copacetic/releases/download/v{{ copacetic.version }}/copa_{{ copacetic.version }}_linux_amd64.tar.gz | \
      tar -xzf - copa
      install -m 555 copa /usr/local/bin/copacetic-{{ copacetic.version }}
      ln -sf /usr/local/bin/copacetic-{{ copacetic.version }} /usr/local/bin/copacetic
  when: not copacetic_bin.stat.exists
