---
- name: Check krew present
  ansible.builtin.stat:
    path: /usr/local/bin/krew-{{ krew.version }}
  register: krew_bin

- name: Install krew
  become: true
  changed_when: true
  ansible.builtin.shell: |
    set -eo pipefail
    curl -L "https://github.com/kubernetes-sigs/krew/releases/download/{{ krew.version }}/krew-linux_amd64.tar.gz" | \
    tar -xzf - krew-linux_amd64
    install -m 555 krew-linux_amd64 /usr/local/bin/krew-{{ krew.version }}
    ln -sf /usr/local/bin/krew-{{ krew.version }} /usr/local/bin/krew
    rm krew-linux_amd64
  when: not krew_bin.stat.exists

- name: Install krew plugins
  become: true
  changed_when: true
  ansible.builtin.shell: |
    krew install neat
    krew install ns
    krew install modify-secret
    krew install tree
