---
- name: Check krew present
  ansible.builtin.stat:
    path: /usr/local/bin/krew-v0.4.5
  register: krew_bin

- name: Install krew
  become: true
  changed_when: true
  ansible.builtin.shell:
    executable: /usr/bin/bash
    cmd: |
      set -eo pipefail
      curl -L "https://github.com/kubernetes-sigs/krew/releases/download/v0.4.5/krew-linux_amd64.tar.gz" | \
      tar -xzf - ./krew-linux_amd64
      install -m 555 krew-linux_amd64 /usr/local/bin/krew-v0.4.5
      ln -sf /usr/local/bin/krew-v0.4.5 /usr/local/bin/krew
      rm krew-linux_amd64
  when: not krew_bin.stat.exists

- name: Install krew plugins
  become: true
  changed_when: false
  ansible.builtin.shell: |
    krew install neat
    krew install ns
    krew install modify-secret
    krew install tree
