---
- name: Check kubectl present
  stat:
    path: /usr/local/bin/kubectl-{{ kubectl.version }}
  register: kubectl_bin

- name: Install kubectl
  become: true
  shell: |
    curl -LO "https://dl.k8s.io/release/{{ kubectl.version }}/bin/linux/amd64/kubectl"
    install -m 555 kubectl /usr/local/bin/kubectl-{{ kubectl.version }}
    ln -sf /usr/local/bin/kubectl-{{ kubectl.version }} /usr/local/bin/kubectl
    rm kubectl
  when: not kubectl_bin.stat.exists
