- name: Argocd
  ansible.builtin.include_tasks: argocd.yaml
- name: Helm
  ansible.builtin.include_tasks: helm.yaml
- name: K9s
  ansible.builtin.include_tasks: k9s.yaml
- name: Kapp
  ansible.builtin.include_tasks: kapp.yaml
- name: Krew
  ansible.builtin.include_tasks: krew.yaml
- name: Kubeconform
  ansible.builtin.include_tasks: kubeconform.yaml
- name: Kubectl
  ansible.builtin.include_tasks: kubectl.yaml
- name: Kubecolor
  ansible.builtin.include_tasks: kubecolor.yaml
- name: Kubeswitch
  ansible.builtin.include_tasks: kubeswitch.yaml
- name: Myks
  ansible.builtin.include_tasks: myks.yaml
- name: Sops
  ansible.builtin.include_tasks: sops.yaml
- name: Stern
  ansible.builtin.include_tasks: stern.yaml
- name: Trivy
  ansible.builtin.include_tasks: trivy.yaml
- name: Vendir
  ansible.builtin.include_tasks: vendir.yaml
- name: Ytt
  ansible.builtin.include_tasks: ytt.yaml
