---
- name: Check stern present
  ansible.builtin.stat:
    path: /usr/local/bin/stern-{{ stern.version }}
  register: stern_bin

- name: Install stern
  become: true
  changed_when: false
  ansible.builtin.shell:
    executable: /usr/bin/bash
    cmd: |
      set -eo pipefail
      curl -L https://github.com/stern/stern/releases/download/v{{ stern.version }}/stern_{{ stern.version }}_linux_amd64.tar.gz | \
      tar -xzf - stern
      install -m 555 stern /usr/local/bin/stern-{{ stern.version }}
      ln -sf /usr/local/bin/stern-{{ stern.version }} /usr/local/bin/stern
      rm stern
  when: not stern_bin.stat.exists

