---
- name: Check ytt present
  stat:
    path: /usr/local/bin/ytt-{{ ytt.version }}
  register: ytt_bin

- name: Install ytt
  become: true
  shell: |
    curl -LO https://github.com/carvel-dev/ytt/releases/download/v0.46.3/ytt-linux-amd64
    install -m 555 ytt-linux-amd64 /usr/local/bin/ytt-{{ ytt.version }}
    ln -s /usr/local/bin/ytt-{{ ytt.version }} /usr/local/bin/ytt
    rm ytt-linux-amd64
  when: not ytt_bin.stat.exists
