---
- name: Check ytt present
  ansible.builtin.stat:
    path: /usr/local/bin/ytt-{{ ytt.version }}
  register: ytt_bin

- name: Install ytt
  become: true
  changed_when: true
  ansible.builtin.shell:
    executable: /usr/bin/bash
    cmd: |
      curl -LO https://github.com/carvel-dev/ytt/releases/download/v0.46.3/ytt-linux-amd64
      install -m 555 ytt-linux-amd64 /usr/local/bin/ytt-{{ ytt.version }}
      ln -f -s /usr/local/bin/ytt-{{ ytt.version }} /usr/local/bin/ytt
      rm ytt-linux-amd64
  when: not ytt_bin.stat.exists
