---
- name: Check OMZ present
  become: true
  become_user: "{{ user.name }}"
  stat:
    path: ~/.oh-my-zsh
  register: omz_bin

- name: Install oh my zsh
  become: true
  become_user: "{{ user.name }}"
  shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --unattended --keep-zshrc"
  when: not omz_bin.stat.exists

- name: Install OMZ theme && plugins
  become: true
  become_user: "{{ user.name }}"
  shell: |
    echo 'export ZSH="/home/fritz/.oh-my-zsh"' >> ~/.zshrc
    echo 'ZSH_THEME="afowler"' >> ~/.zshrc
    echo 'plugins=(colorize urltools sudo git docker kubectl web-search helm)' >> ~/.zshrc
    echo 'source $ZSH/oh-my-zsh.sh' >> ~/.zshrc
  when: not omz_bin.stat.exists
