---
- name: Check OMZ present
  become: true
  become_user: "{{ user.name }}"
  stat:
    path: ~/projects/github/ohmyzsh
  register: omz_dir

- name: Git checkout OMZ
  become: true
  become_user: "{{ user.name }}"
  git:
    repo: 'https://github.com/ohmyzsh/ohmyzsh.git'
    dest: ~/projects/github/ohmyzsh
  when: not omz_dir.stat.exists

- name: Copy zshrc
  copy:
    src: ../../../../templates/zshrc.sh
    dest: ~/.zshrc
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0644'
  become: true
  become_user: "{{ user.name }}"
