---
- name: Git checkout OMZ
  become: true
  become_user: "{{ user.name }}"
  git:
    repo: 'https://github.com/ohmyzsh/ohmyzsh.git'
    dest: ~/projects/github/ohmyzsh
    update: yes

- name: Git checkout FMZ
  become: true
  become_user: "{{ user.name }}"
  git:
    repo: 'https://github.com/fritzduchardt/fritzmyzsh.git'
    dest: ~/projects/github/fritzmyzsh
    update: yes

- name: Copy zshrc
  copy:
    src: ../../../../templates/zshrc.sh
    dest: ~/.zshrc
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0644'
  become: true
  become_user: "{{ user.name }}"
