download_urls:
  bat: https://github.com/sharkdp/bat/releases/download/{{ versions.bat }}/bat-{{ versions.bat }}-arm-unknown-linux-musleabihf.tar.gz
  fd: https://github.com/sharkdp/fd/releases/download/{{ versions.fd }}/fd-{{ versions.fd }}-arm-unknown-linux-musleabihf.tar.gz
  fzf: https://github.com/junegunn/fzf/releases/download/{{ versions.fzf }}/fzf-{{ versions.fzf }}-linux_armv7.tar.gz
  lazydocker: https://github.com/jesseduffield/lazydocker/releases/download/v{{ versions.lazydocker }}/lazydocker_{{ versions.lazydocker }}_Linux_arm64.tar.gz
  lazygit: https://github.com/jesseduffield/lazygit/releases/download/v{{ versions.lazygit }}/lazygit_{{ versions.lazygit }}_Linux_arm64.tar.gz
  mcfly: https://github.com/cantino/mcfly/releases/download/{{ versions.mcfly }}/mcfly-{{ versions.mcfly }}-arm-unknown-linux-gnueabi.tar.gz
  rg: https://github.com/BurntSushi/ripgrep/releases/download/{{ versions.rg }}/ripgrep-{{ versions.rg }}-armv7-unknown-linux-musleabihf.tar.gz
  yq: https://github.com/mikefarah/yq/releases/download/{{ versions.yq }}/yq_linux_arm64.tar.gz
  zoxide: https://github.com/ajeetdsouza/zoxide/releases/download/v{{ versions.zoxide }}/zoxide-{{ versions.zoxide }}-armv7-unknown-linux-musleabihf.tar.gz

